### ISSUE TITLE
kAppNav installed with kabanero shows "unknown" status for application

### ISSUE THREAD

**Issue by gecock** [kabanero-io/kabanero-foundation#101]
kAppNav dashboard shows application status as `unknown`

- Installed kAppNav using kabanero install.
- Configured Tekton webhook to deploy Java MicroProfile application. 
- Application running fine and application pod is running fine.

![image](https://media.github.ibm.com/user/8554/files/081ce480-ee01-11e9-947d-73fd7e4890c9)

**Comment by marikaj123** [comment]
kNavvApp Issue: https://github.com/kappnav/Issues/issues/51

**Comment by marikaj123** [comment]
Paul will provide the updates to kAppNav then the Kabanero installer script will contain the appropriate agreed on kAppNav label. 
SVT team will test the scenario next week.

**Comment by gecock** [comment]
https://github.com/kappnav/Issues/issues/51 has been verified, closing this
