### ISSUE TITLE
Kabanero Collection Validation Pipeline Step should be clearer.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#102]
Users who have not updated their Appsody CLI repo to point at kabanero collections instead of appsody applications are confused about why their builds fail.  This is intentional, and is actually one of the value propositions of Kabanero -- but we should explain that the specific collection they are trying to build is not activated in the Kabanero instance for the triggered Pipeline.  We should describe the collection activation proposition.  @smcclem can help with supplying the text.

**Comment by nastacio** [comment]
The person who did not have their appsody cli repo updated is likely not the same as the person who will be notified about the problem. In a team where the developer does not manage the pipeline, we would have a pipeline administrator receiving a build breakage alert and implicitly tasked with notifying the application owner.

At that point, some thoughts would be:
1. Pipeline automatically email application owner or last committer? That is, assuming the pipeline even has mechanisms (credentials, pipeline task, clear network path through firewalls) to perform such action.
2. Pipeline admin performs #1 manually...ouch...
3. Creation of a pipeline runs a precheck run of credentials and 'alignment' between application and pipeline (e.g. app lists an incompatible stack) . Failure still goes back to #1 or #2, but at least it will happen earlier.

**Comment by stephenkinder** [comment]
Issue moved to [kabanero-io/kabanero-pipelines #109](https://github.com/kabanero-io/kabanero-pipelines/issues/109) via [**ZenHub**](https://www.zenhub.com/)
