### ISSUE TITLE
Creating a PR (no merge) cause the application to be re-deployed

### ISSUE THREAD

**Issue by gecock** [kabanero-io/kabanero-foundation#106]
@mtamboli found the following issue:

The problem is that when a PR is created for an application update in Git repository, it just starts the pipeline run and redeploys on top of the the working application. So basically, this PR was not even reviewed and merged by anyone but it still replaces the existing running application which may cause unwanted changed to be redeployed. It there was a separate deployment for testing this PR, this was fine. 

With lack of eventing, there is not much control. But this behavior should be changed to only redeploy when the PR is merged. No action when PR is created. 

There is a pull request to fix this here -- https://github.com/kabanero-io/kabanero-pipelines/pull/73, but it is blocked on this -- https://github.com/kabanero-io/kabanero-foundation/issues/93 and this https://github.com/kabanero-io/kabanero-foundation/issues/94

**Comment by gecock** [comment]
@vtereso can you confirm for us that your PR (https://github.com/kabanero-io/kabanero-pipelines/pull/73) will address this situation? If so can you also confirm we cannot merge it until https://github.com/kabanero-io/kabanero-foundation/issues/93 is completed?

**Comment by anneqm** [comment]
@gecock I believe PR#73 is is also dependent on #94

**Comment by vtereso** [comment]
As per the [release page](https://github.com/tektoncd/pipeline/releases), conditions have been available since 0.6, which was the same release the `$()` interpolation syntax was introduced. Within the next release, the `${}` release was deprecated. There were changes to the experimental code to pass new parameters into the pipeline, which are used by the conditional within my PR. So, Tekton 0.6 and 0.7 are both satisfactory, but the updated experimental code is also necessary to address this.

**Comment by marikaj123** [comment]
Tekton 0.7 is not for the 0.2 release.

**Comment by kvijai82** [comment]
I am planning to experiment with tekton 0.7 next week and can try to see if we can address this issue then but can't get this into 0.2 kab release.  Too many dependency issues to sort out.

**Comment by gecock** [comment]
Thanks all. Appreciate the info. We will revisit this to verify once all these other issues are resolved.

**Comment by marikaj123** [comment]
@gecock - I am removing the label release-0.2 as you seem to be in agreement with Vijai's comment.

**Comment by kvijai82** [comment]
The long term fix is in the new set of pipelines we are delivering in this release to work with the eventing framework.  We have a pipeline that will only do a build based on PRs and another that will build & push once a PR is merged.  Both of these will not deploy.  Idea here is there will be very specific pipelines for specific triggers.  

Having said that, will see what we can do to fix the issue in the existing build-deploy pipeline.  As of now don't have the conditional path working.

**Comment by stephenkinder** [comment]
Issue moved to [kabanero-io/kabanero-pipelines #107](https://github.com/kabanero-io/kabanero-pipelines/issues/107) via [**ZenHub**](https://www.zenhub.com/)
