### ISSUE TITLE
Put an asterisk studded box at end of foundation script

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-foundation#109]
Put an asterisk studded box at end of foundation script to make the apply command pop out for the Kab CR instance

to highlight:

```
The installation script is complete.  You can now create an instance
of the Kabanero CR.  If you have cloned and curated a collection set,
apply the Kabanero CR that you created.  Or, to create the default 
instance:
oc apply -n kabanero -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.2.0/config/samples/default.yaml
```

**Comment by davco01a** [comment]
the output from long scripts is like reading legal disclaimers for software

**Comment by davco01a** [comment]
*************************************************************************************************
* The installation script is complete.  You can now create an instance
* of the Kabanero CR.  If you have cloned and curated a collection set,
*apply the Kabanero CR that you created.  Or, to create the default 
* instance:
* .     oc apply -n kabanero -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/0.2.0/config/samples/default.yaml
*************************************************************************************************

**Comment by stephenkinder** [comment]
@davco01a feel free to submit a PR.

**Comment by davco01a** [comment]
https://github.com/kabanero-io/kabanero-foundation/pull/111

**Comment by dacleyra** [comment]
Sparkle box exists in 0.3.0 install script
https://github.com/kabanero-io/kabanero-operator/releases/download/0.3.0-rc.1/install.sh

Closing
