### ISSUE TITLE
Integration testing of Tekton Webhook Extension & Dashboard and Kabanero 0.3.0

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#115]
As part of the delivery of 0.3.0, we need to make sure we do an integration test of specifically the Tekton Webhook Extension and Dashboard in the context of the OCP 4.2 release of Kabanero.

**Comment by marikaj123** [comment]
@anneqm - Need someone to help with testing theis issue

**Comment by kvijai82** [comment]
We created a webhook and created a PR in the git repo that triggered a pipeline run successfully.

**Comment by aadeshpa** [comment]
yes, we verified in openshift 4.2 cluster by creating a webhook, and that triggered a pipeline on a new pull request in the github.
