### ISSUE TITLE
Integration testing of Appsody Serverless function in the Context of Kabanero 0.3.0.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#116]
We need to add additional Appsody tests to ensure that the Serverless deploy capability properly behaves in the context of Kabanero 0.3.0.

This integration test is a kick-the-tires test to make sure that an Appsody application that intended to be deployed as serverless, can be wired through a github webhook to our build and deploy pipeline, hosted in a kabanero instance.  

The application should be verified to be able to scale to zero, and scale up when a request hits the route.

Note:  The appsody operator team should already have test projects that have been verified in Kubernetes, the intention of this integration is to ensure that the same behavior correctly works in a Kabanero deployment in OCP 4.2.

**Comment by marikaj123** [comment]
Dan is looking after automation.

**Comment by marikaj123** [comment]
@dacleyra - Is the work for the issue on track to complete by Nov-15?

**Comment by dacleyra** [comment]
@kaczyns @stephenkinder 

Looking for an opinion here

Tekton drives their tests with a manual pipelinerun using bash shell scripting
https://github.com/tektoncd/dashboard/tree/master/test

Appsody drives their tests using go
https://github.com/appsody/appsody-operator/tree/master/test/e2e


What I believe we need to do to achive an e2e is

1. Create an appsody init application of each collection type, and commit them each to a repo in the kabanero-io org
2. Set the appsody deploy yaml for each application to serverless
3. Decide **whether to script in bash shell script, or write the test in go**
4. Execute the tests using manual pipelinerun

A webhook run test I don't think currently exists for Tekton, answer pending.

**Comment by kaczyns** [comment]
Just my opinion here... I don't think that either approach would be bad.  The things I have been thinking about are:
1) Is the test going to install Kabanero to a cluster as well.  If so, it will probably want to leverage the install shell script, and so having the tests themselves being scripted in bash would not be too much additional work.
2) Writing in go lets us leverage the built-in testing framework which the kab operator already wants to use.  I don't know what frameworks exist in bash, I'm sure there is something, but go feels like a more natural fit.  But I think to be able to do this, the test has to be provided with a cluster that already has Kabanero operator and its prerequisites installed on it.
3) The clients and go mappings of the various CRDs would make it easier to query/scrape things like a pipeline run to see how it is progressing.  I don't know how easy it is to extract debug information using Go though (I am thinking that if there is a failure, or maybe even if there is not, we're going to want to get container logs and things like that and save them with the test results).  that process is pretty straightforward in bash.

**Comment by kvijai82** [comment]
Just wanted to mention that @smcclem started working on a script to manually drive all pipelines for all the active collections and validate the app deployed.  Now this is not serverless, but I guess we could modify the app-deploy.yaml to make it.

@StringCheeseCR was looking into picking this up and figuring out the infrastructure to drive this and run this as our daily integration test.

**Comment by dacleyra** [comment]
Serverless deployment is blocked by
https://github.com/appsody/appsody-operator/issues/183

Some progress has been delivered
https://github.com/kabanero-io/kabanero-operator/pull/295

Can continue to make progress on adding the tests for remaining stacks, but attempting to test for app state, and endpoint will fail.

**Comment by dacleyra** [comment]
Test completion blocked by

Impacts java- collections
https://github.com/kabanero-io/collections/issues/174

Impacts nodejs-loopback collection
https://github.com/kabanero-io/collections/issues/177

**Comment by marikaj123** [comment]
According to Daniel:  About 90% done with writing the automation/tests.  Blocked by the collection issues, 174 and 177, with the fix to test the app endpoint.
The fix https://github.com/kabanero-io/collections/issues/174 should go into the next collection v0.3.0-RCx
kabanero-io/collections#177 needs to fix the Loopback collection.

**Comment by dacleyra** [comment]
code is thought to be complete, but the blockering bugs for test completion still need to be resolved

**Comment by dacleyra** [comment]
Impacted by
https://github.com/kabanero-io/kabanero-pipelines/issues/126

**Comment by marikaj123** [comment]
DANIEL CLEYRAT:
the tests don't pass because of the other issues that cause the tests to fail - they are noted in the issue

**Comment by dacleyra** [comment]
Tests complete successfully with 0.3.0-rc.5
