### ISSUE TITLE
Pipelines unable to use internal registry images created during collection curation

### ISSUE THREAD

**Issue by bconey** [kabanero-io/kabanero-foundation#117]
If a user chooses to use their internal registry for pushing images of the stack (java MicroProfie) as part of collection curation, pipeline is still looking at docker hub for the image. If image does not exist in docker hub, pipeline run will fail.  There is no way to tell the pipeline to use the internal registry location to find the stack images.

So in the following example of the assemble-extract step it shows `Pulling docker image kabanero/java-microprofile:0.2` it should be using image `java-microprofile    docker-registry.default.svc:5000/kabanero/java-microprofile`

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/31766760/67785360-712c6b00-fa43-11e9-9a5c-99548b95a885.png">

**Comment by stephenkinder** [comment]
Issue moved to [kabanero-io/kabanero-pipelines #101](https://github.com/kabanero-io/kabanero-pipelines/issues/101) via [**ZenHub**](https://www.zenhub.com/)
