### ISSUE TITLE
Update pre-requisites for Kabanero 0.3.0 using OCP 4.2.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#119]
The README.md file needs to be updated with the pre-requisites for 0.3.0, specifically because the base Kubernetes distribution is changing from OKD 3.11 to OCP 4.2.

**Comment by dacleyra** [comment]
@stephenkinder 

Prereqs were updated on foundation pages README, as well as the container scheduling requirements scrape

https://github.com/kabanero-io/kabanero-foundation

Let me know if there's any other details you want.
