### ISSUE TITLE
Dependent Project upgrade Tekton 0.8 Pipelines

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-foundation#123]
Would like to investigate if we can pull in tekton 0.8 in the next release (0.4.0) as it contains fixes for a couple of issues we have in pipelines.

**Comment by stephenkinder** [comment]
Issue moved to [kabanero-io/kabanero-pipelines #106](https://github.com/kabanero-io/kabanero-pipelines/issues/106) via [**ZenHub**](https://www.zenhub.com/)
