### ISSUE TITLE
Tekton dashboard not accessible with Kabanero 0.3 on OCP4.2

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#126]
1. Installed kabanero 0.3 on OCP4.2 
2. Created a default kabanero instance. 
3. Tekton dashboard is not accessible from the URL found from the routes
```
Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
```

**Comment by mtamboli** [comment]
FYI, @dacleyra @marikaj123

**Comment by marikaj123** [comment]
@anneqm - @dacleyra is looking after this issue and I have added your team in case your help will be needed.

**Comment by mtamboli** [comment]
Landing page is not accessible either after installing Kabanero.

**Comment by csskinner25** [comment]
I see an issue that the kabanero landing page will not load. The error is 
An error occurred during a connection to kabanero-landing-kabanero.apps.css.os.fyre.ibm.com. PR_END_OF_FILE_ERROR 

Is this the same error?

**Comment by dacleyra** [comment]
Service Mesh Operator v1.0.1 installed

Tekton Dashboard installed
https://github.com/tektoncd/dashboard/releases/tag/v0.2.1

ServiceMeshMemberRoll includes namespace tekton-pipelines

Notably, tekton dashboard has this route

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tekton-dashboard
  namespace: tekton-pipelines
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: Reencrypt
  to:
    kind: Service
    name: tekton-dashboard
```

Sometimes it is possible to route to this (https://tekton-dashboard-tekton-pipelines.apps.subdomain/)
Sometimes it reports not available

Restarting Router and allowing only 1 instance, 
sometimes on router restart the dashboard is available
sometimes on router restart the dashboard is not available

`oc patch -n openshift-ingress-operator ingresscontroller/default --patch '{"spec":{"replicas": 0}}' --type=merge`
`oc patch -n openshift-ingress-operator ingresscontroller/default --patch '{"spec":{"replicas": 1}}' --type=merge`

Removing the tekton-pipelines from the ServiceMeshMemberRoll clears up the problem

Same cause for landing page

**Comment by dacleyra** [comment]
Case #02512560 is opened with RedHat for the issue.

To access the dashboards, the temporary workaround is to edit & remove the namespaces from the servicemeshmemberoll 

`oc edit -n istio-system servicemeshmemberroll default`

**Comment by a-roberts** [comment]
Bear in mind the above approach is going to mean you won't be able to receive and handle webhook events correctly owing to our reliance on Knative still

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/serverless_applications/installing-openshift-serverless see 
```
Add all namespaces to which you want to deploy serverless applications. Ensure you retain the knative-serving namespace in the member roll.
```

https://github.com/tektoncd/experimental/pull/326 documented workaround I propose

**Comment by a-roberts** [comment]
^^ please see my updated PR which mentions a working NetworkPolicy config and some reasoning as to why this is happening courtesy of a super helpful RedHatter.

I haven't investigated as to whether this policy exposes any other issues or thoroughly SVTed it, but at least the route is accessible while the namespace is enrolled in the ServiceMesh.

**Comment by csskinner25** [comment]
New work around to supersede the old way.
Create a yaml file on your system with this content
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: allow-all
spec:
 podSelector: {}
 ingress:
 - {}
 policyTypes:
 - Ingress
Run these commands using the yaml file your created.
oc apply -n tekton-pipelines -f newnet.yaml
oc apply -n kabanero -f newnet.yaml
If you had removed the member from the previous instructions , put them back
members:
 - kabanero
 - tekton-pipelines
 - knative-serving (edited)

**Comment by kaczyns** [comment]
kabanero-io/kabanero-operator#289 is merged.  I propose to create another RC release this afternoon.  Will discuss on the status call today.

**Comment by marikaj123** [comment]
Action:  Cut a new rc release today

**Comment by marikaj123** [comment]
@kaczyns - does Monica have what is needed to verify and close this issue?

**Comment by kaczyns** [comment]
@marikaj123 Yes Monica needs to install Kabanero 0.3.0-rc.2 and re-test.

**Comment by mtamboli** [comment]
Closing the issue as this problem does not happen anymore.
