### ISSUE TITLE
Codewind not able to work with stacks images in the internal registry/non-docker hub

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-foundation#127]
Codewind:  https://github.com/eclipse/codewind/issues/938

kabanero does not need to make any change for this fix though

**Comment by marikaj123** [comment]
Codewind team are focused to resolve the issue ASAP.

**Comment by marikaj123** [comment]
According to Steven, the target is for the December 4th DCUT. It is being tracked by https://github.com/eclipse/codewind/issues/948 (epic) and also #938.
The workaround that was investigated a little while back is not recommended by the user. They have to make manual and tedious changes that may need to be done multiple times (if a new container is created).

**Comment by marikaj123** [comment]
For v0.3.0 release, we need a workaround to publish to somewhere for the customer to get the interm fix until the fix will be completed by early Dec. Che will need to pick the interm fix.
A proper fix will be available in early December.
It is not a stopship since the issue existed in previous releases.

**Comment by sghung** [comment]
Once the fix from codewind is done in early December, the testers can verify it using the new codewind dev file (see instructions here): https://www.eclipse.org/codewind/installoncloud.html#creating-the-codewind-workspace-with-a-devfile

**Comment by marikaj123** [comment]
Che UI to manage credentials will be done by tomorrow. 
The local case will be documented the workaround solution. 
Codewind 0.7.0 D-cut on Dec-4 will contain the Che fix.

**Comment by sghung** [comment]
Still waiting on the 0.7.0 dev file to be released by Codewind. Some issues came up yesterday so it not ready yet.

**Comment by sghung** [comment]
@marikaj123 I just got word that testing can be done on our latest dev file (as 0.7.0 isn't created yet). Please have the developer try: https://github.com/eclipse/codewind-che-plugin/blob/master/devfiles/latest/devfile.yaml as part of the instructions https://www.eclipse.org/codewind/mdt-che-installinfo.html#creating-the-codewind-workspace-with-a-devfile

**Comment by marikaj123** [comment]
@mtamboli - For your awareness.

**Comment by marikaj123** [comment]
Codewind-che-plugin 0.7.0 may cut around Dec 12.

**Comment by marikaj123** [comment]
According to the codewind team received some feedback from SVT and is trying to incorporate it into the Codewind-che-plugin 0.7.0.

**Comment by marikaj123** [comment]
https://github.com/eclipse/che/issues/15389  - Is a Che issue not Codewind so Codewind will have to wait for their fix.

**Comment by marikaj123** [comment]
The codewind defect is https://github.com/eclipse/codewind/issues/938 is targeted for codewind 0.9.0 with GA of Feb 20th.

**Comment by marikaj123** [comment]
Monica, is looking to verify the workaround solution.

**Comment by marikaj123** [comment]
According to Marylin, A fix may not be required for https://github.com/eclipse/codewind/issues/938
The kabanero team is currently testing a workaround and if that is successfully, Codewind will only need to doc the workaround steps. Here’s the latest update from our Dev and included in the defect:
“We had a meeting on Feb 3rd with the Kabanero folks + Jag. They agreed that the fully qualified stack name in their project is an appropriate solution. Previously, before that was a standard for Appsody stacks, they were more resistant to it. If this approach works, we will document it. I will followup with the contact person today.”

**Comment by marikaj123** [comment]
According to Monica:  From what we tried earlier, it seems like the suggested workaround should work although we could not fully test it as discussed.
@sghung @makandre Please document the workaround. We will try to verify the workaround in our next release testing.
Do you still want to keep the defect open for the final fix and reduce the severity?

**Comment by makandre** [comment]
If the `stack:` property in the project's `.appsody-config.yaml` file **is fully qualified** out-of-the-box, i.e. it is of the form `hostname[:port]/username/reponame[:tag]`, do this:

1. On the local system, do a `docker login` to the private registry

If the `stack:` property is **not fully qualified**, i.e. it is of the form `username/reponame[:tag]`, do these additional steps:

2. Edit the local system's `~/.appsody/.appsody.yaml` file, change the `images` property from the default `docker.io` to the private registry host

3. Then create the project and afterwards, edit the project's `.appsody-config.yaml` file and change the `stack:` property to be fully qualified

**Comment by marikaj123** [comment]
The workaround works and it will be tracked by the codewind team.
