### ISSUE TITLE
Review/update MustGather scripts

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-foundation#133]
Review/update MustGather scripts for Kabanero 0.3.0 and OCP 4.2

**Comment by dacleyra** [comment]
needs to scrape tekton-pipelines namespace for dashboard info

**Comment by marikaj123** [comment]
@kvijai82 and @tseelbach - can we add additional tekton/pipeline debug?
@mnuttall - the pipeline team may need your help as well. 
@makandre - would you be able to help from the Che side to provide updates related to the che diagnostics

**Comment by rtaniwa** [comment]
We shouldn't be assigning people without having discussions about what is actually required, and there is nothing in this issue that provides that level of detail. As far as I am aware, none of my folks have been involved in any discussions about must gather for Kabanero.

**Comment by tseelbach** [comment]
@jgawor - @kvijai82 said he can take a look tomorrow a.m.  Where are the scripts to review?

**Comment by jgawor** [comment]
https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts/mustgather

**Comment by kvijai82** [comment]
Made a small addition to the kabanero must gather script in https://github.com/kabanero-io/kabanero-foundation/pull/147

**Comment by kvijai82** [comment]
PR is merged.  Done from pipelines perspective.  Not sure if this was meant for just pipelines or other components also.  If it's just pipelines, it can be closed.

**Comment by marikaj123** [comment]
@jgawor  - Is the issue good to close?

**Comment by jgawor** [comment]
Yes. Thanks. Please keep in mind that all teams should be reviewing/updating these scripts periodically.
