### ISSUE TITLE
Prepare for next release of Tekton Dashboard with Webhooks Extension 0.3.0 and Tekton Triggers 0.1.0

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-foundation#140]
Kabanero Tekton Upgrade to next release of Tekton Dashboard and Webhooks Extension 0.3.0 with Tekton Triggers 0.1.0 remove dependency on knative and Istio/Service Mesh and add use of Tekton Triggers. Value statement: results in smaller footprint and increased reliability as this change removes breakage that comes when OCP changes underlining dependencies on knative and Istio outside our control. 

This issue addresses the Tekton aspects to prepare for next release, see https://github.com/kabanero-io/kabanero-foundation/issues/87. 

See related issues:
https://github.com/kabanero-io/docs/issues/225
https://github.com/kabanero-io/kabanero-operator/issues/329
https://github.com/kabanero-io/kabanero-pipelines/issues/145

**Comment by anneqm** [comment]
@marikaj123 @stevekinder-ibm Please note that v0.3.0 releases of the Tekton Dashboard and Webooks Extension is now available at https://github.com/tektoncd/dashboard/releases/tag/v0.3.0.

**Comment by marikaj123** [comment]
@anneqm - The Kabanero team is aware of this now. Please feel free to close the issue when your team is done.

**Comment by anneqm** [comment]
@marikaj123 This Epic should also have the associated pipelines and operator issues linked to it. The documentation task is now finished, but the pipeline and operator work is still ongoing.  I don't think we should close this one until those are finished as well: 
kabanero-io/kabanero-operator#329
kabanero-io/kabanero-pipelines#145

**Comment by marikaj123** [comment]
@anneqm - The Kabanero team is planning to include Tekton 8.0 and Tekton Dashboard and Webhooks Extension 0.3.0 with Tekton Triggers 0.1.0. The above issues will be closed towards the end of this week. Thank you for providing us with what is needed.

**Comment by anneqm** [comment]
Noticed kabanero-io/kabanero-pipelines#145 is now closed.

**Comment by anneqm** [comment]
https://github.com/kabanero-io/kabanero-operator/issues/329 is now closed so will now close this Epic.
