### ISSUE TITLE
Kabanero Dependncies on Open Source Feeder Projects

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-foundation#149]
List of latest dependencies for Kabanero collection and Operator to include in Kabanero v0.5.0.
Nodejs-loopback - Pull v0.1.8.
https://github.com/appsody/stacks/blob/master/incubator/nodejs-loopback/stack.yaml#L2
Working on adding the rest of the dependencies here.

**Comment by groeges** [comment]
0.2.18 version of the nodejs-loopback stack has been merged into the Kabanero nodejs-loopback collection  and will therefore be included in the 0.5.0 release.

**Comment by marikaj123** [comment]
Work is in progress and will be included as part of the 0.5.0 GMC release.

**Comment by marikaj123** [comment]
@kaczyns - Is this issue ready to close?

**Comment by kaczyns** [comment]
I see that the nodejs-loopback stack v0.1.8 is in the 0.5.0-rc.3 collection index.  I am closing this issue.
