### ISSUE TITLE
Pipleline reruns are failing 

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#153]
After putting kabanero 0.4 collections. Piplelineun run is completing successfully but the rerun is failing as it is using incorrect service account name of `pipeline` instead of `Kabanero-pipeline`.

**Comment by mtamboli** [comment]
Let us understand why this is happening and the fix for this. @kvijai82 and Adam Roberts are aware of this and looking into it.

**Comment by marikaj123** [comment]
@anneqm - Hi Anne, we have a stopship defect for Kabanero release 0.5.0 and Adam R. is looking at it.

**Comment by mtamboli** [comment]
This problem was in old version of dashboard as I still had rc2 kabanero operator. After new Tekton dashboard 0.4.1 was installed and new pipeline was run, rerun worked fine.
