### ISSUE TITLE
Kabanero install script fails on Openshift-4.3.0

### ISSUE THREAD

**Issue by raguks** [kabanero-io/kabanero-foundation#154]
Following the instructions here and see the failure below.
https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html

```
++ oc get installplan install-zb5ld -n kabanero '--output=jsonpath={.status.phase}'
+ PHASE=Failed
+ sleep 2
```

Please let me know more information you may need to look at this issue.

**Comment by raguks** [comment]
Just an update. It actually brings the openshift cluster down. The script eventually fails:
```
++ oc get installplan install-zb5ld -n kabanero '--output=jsonpath={.status.phase}'
+ PHASE=Failed
+ sleep 2
+ '[' Failed == Complete ']'
++ oc get installplan install-zb5ld -n kabanero '--output=jsonpath={.status.phase}'
Unable to connect to the server: EOF
```

**Comment by marikaj123** [comment]
@raguks - Please update the issue based on the input you received from Tim.  Thank you.

**Comment by marikaj123** [comment]
According to Ragu, he was able to install on 3x3 Os4.3 using 4.3 install scripts. The issue seems to be 1x3 Fyre cluster.  he has not verified the installation yet. He will do that today and update the issue. He thinks you can lower the priority.

**Comment by raguks** [comment]
I was able to install on 3x3 Os4.3 using 4.3 install scripts. Issue seems to be that of 1x3 Fyre cluster. I have not verified the installation yet. I will do that today and update the issue. I think you can lower the priority. I will close as soon as I verify. Thanks to Tim and your team for the help.

**Comment by raguks** [comment]
Hi while install went okay and I have run the oc apply as asked by the install script, I do not see the Kabanero tab in the console. There is no documentation on fixing self signed certificate. I cant seem to find ```/etc/origin/master/master-config.yaml``` on say master-1. Can you please direct me a bit or update the documentation?

**Comment by raguks** [comment]
I was able to access the console and move on. Still dont see the tab though. I can help someone update the docs a bit when I am through this. Discover and Try can be made bit easier I think. Let me get through first. Thanks for all the help.

**Comment by kaczyns** [comment]
@raguks there is no longer a kabanero tab on the console.  can you please let me know where you are seeing something in the doc that alludes to this so that we can remove it?  I'd like to close this issue since you got thru the install OK, and work these other things in separate issues.  Please let me know if you agree.  Thanks!

**Comment by raguks** [comment]
https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html
![image](https://user-images.githubusercontent.com/680244/73783871-6f6cf480-4762-11ea-8821-840f14bb1e89.png)

We need to add clear direction on what to do after installation. ```appsody deploy``` and Kabanero whats the connection needs to be explained clearly in what to do after the install.

**Comment by raguks** [comment]
Yes separate issue - not a bug but documentation. However 1 master 3 worker install still had issues - you may want to document the errors above in install troubleshooting.

**Comment by marikaj123** [comment]
@kaczyns - Any suggestion who can own this defect to help with the documentation.

**Comment by kaczyns** [comment]
@raguks Please see https://github.com/kabanero-io/docs/pull/299 and let me know if it meets your expectations.  Thanks!

**Comment by marikaj123** [comment]
@kaczyns - According to Ragu: "Yes please go ahead - but please get an end to end review from someone."

**Comment by marikaj123** [comment]
Work is merged
