### ISSUE TITLE
Pre 0.5 releases incompatible with Appsody CLI 0.55 / 0.66

### ISSUE THREAD

**Issue by kilnerm** [kabanero-io/kabanero-foundation#156]
### Problem Symptoms
Build pipelines will fail when run against applications initialized using the following versions of the Appsody CLI: 0.5.5, 0.5.6

The symptom will be apparent for Kabanero releases prior to 0.5

### Underlying cause
The meta-data for a Kabanero collection contains an image reference in the format image_org/image_name. eg, kabanero/nodejs.

This meta-data is recorded in the Kabanero instance when the collection is installed.

The build pipeline will compare the value of the image specified in the applications configuration with the meta-data in the Kabanero instance. If the applications image is active in the Kabanero instance the pipeline will continue, if not the build will fail.

The latest Appsody CLI is now automatically appending the image registry to the application configuration so an application initialised from the nodejs collection would now contain an image tag in the form docker.io/kabanero/nodejs.

This change results in the pipeline check failing.

### Known workarounds
After initializing an application the .appsody-config.yaml in the application source folder can be edited to remove the docker registry portion of the image tags value.

### Proposed solution
Update the Appsody CLI so it no longer inserts the image registry when the default template does not contain one.

### Alternative solution
Release fix updates for all in-service releases of Kabanero collections (and ICP4A?) to add fully qualified image tags to the generated indexes.

**Comment by kilnerm** [comment]
https://github.com/appsody/appsody/issues/871 is open to evaluate the possibility of reverting the change in CLI behavior. 

Further enhancements in the Kabanero 0.5 and 0.6 releases and Appsody CLI will ensure a better integrated solution.

**Comment by kilnerm** [comment]
I swapped the enhancement label for bug as this is a defective behavior on in-service releases. This issue is primarily for driving the necessary documentation into the service channels so people are able to identify the issue when encountered, identify the workarounds and once available document the fix.

**Comment by kilnerm** [comment]
Appssody 0.5.8 resolves the incompatibility with older collections releases. 

@marikaj123 Do we have a mechanism to document known issues and solutions?

**Comment by marikaj123** [comment]
Hi @kilnerm - according to @jantley-ibm the ID team could help with setting up a separate page just for known issues if troubleshooting is not a good fit.  Let us know who would be the appropriate team members to contribute to the content.

**Comment by marikaj123** [comment]
Vijai will follow-up with Jeff for the doc.

**Comment by jantley-ibm** [comment]
doc is being tracked in https://github.com/kabanero-io/docs/issues/289
closing this as dupe
