### ISSUE TITLE
Move up to Tekton Dashboard (0.5.1), Pipelines (0.10.1), Triggers (0.2.1)

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-foundation#157]
Move up to latest Releases:

- Tekton Dashboard and Webhooks Extension (0.5.2 version available 
- Tekton Pipelines 0.10.1
- Tekton Triggers 0.2.1

This is needed in order to pick up the fix for the scalability issue https://github.com/kabanero-io/kabanero-foundation/issues/150

Child issues:
https://github.com/kabanero-io/kabanero-pipelines/issues/188
https://github.com/kabanero-io/kabanero-operator/issues/441
https://github.com/kabanero-io/kabanero-operator/issues/407
https://github.com/kabanero-io/kabanero-pipelines/issues/165
https://github.com/kabanero-io/kabanero-operator/issues/478   (move operator up to 0.5.2)

In order for kabanero to easily use the openshift operator, it is from community-operator repo:
https://github.com/operator-framework/community-operators/tree/master/community-operators/openshift-pipelines-operator

In addition, we can monitor the openshift repos to watch here for progress:
Openshift Pipeline: https://github.com/openshift/tektoncd-pipeline/releases
Openshift Triggers: https://github.com/openshift/tektoncd-triggers/releases
*Also can check branches to see dev-preview releases (available now)
**Operator PRs:** https://github.com/operator-framework/community-operators/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by marikaj123** [comment]
@anneqm - Kabanero will be including the OpenShift Tekton Operator version 0.10.1.  Please provide us with the links where they are available.

**Comment by anneqm** [comment]
@marikaj123 This one is also blocked by the availability of the openshift-pipelines-operator.

**Comment by anneqm** [comment]
Tekton Dashboard and Webhooks Extension 0.5.1 is now available for the team to get started. https://github.com/tektoncd/dashboard/releases/tag/v0.5.1

**Comment by anneqm** [comment]
Tekton Dashboard and Webhooks Extension 0.5.2 is now available for the team to move up to: https://github.com/tektoncd/dashboard/releases

**Comment by anneqm** [comment]
@marikaj123 Can we remove the blocked by labels?  all the child tasks are done.. we are just waiting for @tam512 or someone else in SVT to confirmation that the webhook scalability issue is resolved and for SVT to close  issue #150 .

**Comment by anneqm** [comment]
Since all referenced child issues and the webhook scalability issue are closed.. closing this now. Thanks, everyone!
