### ISSUE TITLE
Bug:  Kabanero uninstall should remove kabanero namespace

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-foundation#162]
Currently Kabanero 0.5.0 uninstall only deletes the relevant Tekton namespace but not the kabanero namespace.  Please remove and cleanup kabanero namespace after uninstall it.

**Comment by tkulik** [comment]
I still see the same problem with kabanero 0.6.0 version.

**Comment by marikaj123** [comment]
Hi @kaczyns - Any idea who can help with looking after this SVT defect?

**Comment by kaczyns** [comment]
@marikaj123 We will go ahead and delete the kabanero namespace in the uninstall script.  As I tried to point out on a call last week, it is likely that we will need to invest significant person resources to diagnose and fix all of the reasons why the uninstall script will now hang when it is deleting the kabanero namespace.

**Comment by kaczyns** [comment]
This is fixed in kabanero-operator 0.6.0-rc.3
