### ISSUE TITLE
create initial prototype of a nightly regression build

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#163]
Minimum requirements:

- run on a regular schedule (once a night, say)
- install a defined release of kabanero into a codeready container and verify installation

**Comment by tomlinkusa** [comment]
So far I have a script that runs the ansible playbook that was in icpa-system-test to create the CRC mostly based on the script that was located in icpa-system-test. @garypicher How do you anticipate scheduling? For WASaaS we have jobs scheduled on a jenkins server.

**Comment by marikaj123** [comment]
@garypicher - We have a prototype and can be closed
