### ISSUE TITLE
design mechanism for plugging tests into the nightly regression build

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#166]

**Comment by tomlinkusa** [comment]
In the icpa-build-and-test repo

icpa-build-and-test
   |
   tests
      |
      <test name>
         |
         test.sh or test.yaml

Tests would be run after the CRC is up.

**Comment by tomlinkusa** [comment]
In the kabanero-regression-test repo

To add a new test, create a unique directory name, in the following format:
`kabanero-regression-test/tests/<test name>`

In that directory place either test.sh or test.yaml. If both files exist only test.sh will run.Tests would be run after the OCP is up and the test machine is logged in.
