### ISSUE TITLE
Todd can install Kabanero Foundation on OpenShift 3.11

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-foundation#17]

**Comment by marikaj123** [comment]
Work will be done by August 12.

**Comment by marikaj123** [comment]
As per Steve's suggestion, the Epic was assigned to you.  Please feel free to assign it to the appropriate person.  The Epic needs to have child issues be associated with it, as well.

**Comment by marikaj123** [comment]
deferred to openshift v3.11

**Comment by kyleschlosser** [comment]
We do not test the Kabanero OSS against commercial offerings, but have verified this on OKD 3.11.
