### ISSUE TITLE
update kabanero repositories to push "development" tag containers from the builds

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#171]
Our Kabanero Travis builds run every time a new pull request is merged into master, however new container images are only pushed to docker hub for "release builds" (i.e. builds initiated by pushing a new tag to the repo).  We need to update the "development" builds (i.e. builds initiated by an update to master) to push a container image to docker hub that represents the absolute latest code from master.  I propose that we call this tag "development" but I'm open to other suggestions.

**Comment by hbtran** [comment]
The nightly tests are now installing the kabanero-operator tagged as master.  The landing and cli are not producing master tagged images at this point.
