### ISSUE TITLE
Unable to launch app with http on CodeReadyWorkspace with tls enabled

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-foundation#173]
This defect is used to track the codewind defect https://github.com/eclipse/codewind/issues/2273
The problem was found when testing CodeReadyWorkpace with tlsSupport enabled

**Comment by marikaj123** [comment]
According to John Collier, he has passed the devfile to @tam512  and gave instructions on how to verify the fix.  The fix is going into a refresh version of codewind 0.8.

**Comment by marikaj123** [comment]
@tam512 - tested the fix and it did work. @tam512 - Are we good to close this defect?

**Comment by tam512** [comment]
Verified with Tim's Che devfile that contains a fix for Theia
