### ISSUE TITLE
Fail to build Open Liberty stack in Codewind in codeReadyWorkspace

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-foundation#174]
Use this defect to track appsody stack defect https://github.com/appsody/stacks/issues/678
The problem was found when testing CodeReadyWorkpace in Kabanero 0.6.0

**Comment by gecock** [comment]
@marikaj123 Given CRW and OL stack are new features in 0.6.0 we believe this needs to be fixed and incorporated into Kabanero 0.6.0 prior to release.

**Comment by marikaj123** [comment]
The issue is opened here: https://github.com/appsody/stacks/issues/678

**Comment by marikaj123** [comment]
Waiting for the rc to be build today.

**Comment by tam512** [comment]
I verified that I can build Open Liberty stack in Codewind in CodeReadyWorkspace using Kabanero Operator 0.6.0-rc.4 with stack hub https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.0-rc.2/kabanero-stack-hub-index.yaml
