### ISSUE TITLE
add support to regression build to print list of installed containers after kabanero install

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#175]
One frequent need we have is to identify what containers are installed by a given version of Kabanero.  It would be useful to have our nightly regression build produce this automatically.  We should add a "test case" or some other section of the build that runs a script after the Kabanero install to list the new containers that were deployed by the install.

@jgawor already has a such a script that he runs manually, so whoever does this task should consult Jarek and use that script as a basis for this support.

**Comment by StringCheeseCR** [comment]
From Tim K as I prodded more about how to get the info we're looking for...
OLM installs operators based on the channel and registry.  Kabanero installs its own catalog, as well as using the red hat catalog and certified catalog (registry).  You subscribe to a channel which is a descriptive name, not a release.  So for the operators in the Kabanero catalog, you could attempt to scan the list of subscriptions for the channel name, and then scan the registry yamls and try to figure out version of each operator is.  But for the ones that come out of the red hat catalog, that won't work.
then, there are more yamls for things like kappnav which you can scan directly and probably figure out the versions.
then there's still more like the tekton dashboard which does HTTP get of the YAML from github, and applies it, so I guess you could scan the shell script for the version and you'd get that.
then there's the internal things (kabanero-command-line-services, kabanero-landing, etc) and there's a different yaml file you can scan to get that.

**Comment by StringCheeseCR** [comment]
Sent initial output to Gary & Tim and got some info back on updates. Working on those,

**Comment by StringCheeseCR** [comment]
Pull request submitted https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/pull/545

**Comment by StringCheeseCR** [comment]
This will be complete as soon as it's reviewed.

**Comment by StringCheeseCR** [comment]
Merged into automation repo
