### ISSUE TITLE
Issues with ksvc using internal registry

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-foundation#176]
https://github.com/knative/serving/issues/5126

I have encountered similar in integration test where the ksvc deployed by appsody will not complete a successful revision due to an x509 certificate error with regards to the internal registry service. When deployed as a standard pod, this is not an issue.

This seems to be an issue introduced in serverless 1.4.1, which is based on knative serving v0.11.1.
I had not observed such an issue previously.

The workaround as it relates to the integration test is handled in PR
https://github.com/kabanero-io/kabanero-operator/pull/521

@arthurdm
@mtamboli 
@kaczyns

**Comment by marikaj123** [comment]
@kaczyns - Does the issue continue to exist in Kabanero 0.8.0 after moving to Servless 1.5.0?

**Comment by kaczyns** [comment]
I'd like @dacleyra to comment on that.... the issue he refers to is still open.  I have not tried to re-create this issue.
