### ISSUE TITLE
Bug: With knative enabled the pods don't scale down

### ISSUE THREAD

**Issue by tkulik** [kabanero-io/kabanero-foundation#180]
I have created a deployment for java-microprofile app using knative enabled and I dont see the pods scaling down when app is inactive. I am using kabanero 0.6.0 rc5 with OpenShift 4.3.

To Reproduce

1. Deploy java-microprofile app with knative enabled
2. Use webhook to start the pipeline
3. Verify that the app is working, then close the browser, wait for some time, and watch the pods. They never scale down to 0, still show 1 of 1 running in the Gui.

at cmd line I see these pods running:

oc get pods | grep kab06
kab06javamp-wfmsg-deployment-78864666b7-xwz4x                     2/2     Running     0          48m

oc get AppsodyApplication kab06javamp -o yaml cmd shows knative enabled:

spec:
  applicationImage: image-registry.openshift-image-registry.svc:5000/kabanero/kab06javamp:9e67855d61b2d4c4231162b39f73d20ff45a915d
  createKnativeService: true
  expose: true

The app was deployed using appsody

 oc get AppsodyApplications
NAME          IMAGE                                                                                                            EXPOSED   RECONCILED   AGE
kab06javamp   image-registry.openshift-image-registry.svc:5000/kabanero/kab06javamp:9e67855d61b2d4c4231162b39f73d20ff45a915d   true      True         125m

I see the same behavior with nodejs-express and java-spring-boot apps. With knative enabled the pods dont scale down.

![image](https://user-images.githubusercontent.com/21961572/75383699-74751d80-58a2-11ea-90f5-b70ccefa007b.png)

Environment Information:

Kabanero/ICPA Version: 0.6.0-rc.5
OpenShift Version: 4.3
Platform (Fyre, IBM Cloud, etc): Fire cluster with 3 workers and 3 masters

**Comment by marikaj123** [comment]
Navid is driving this issue.

**Comment by tkulik** [comment]
Navid provided a fix, and I have verified.  The problem is fixed.

**Comment by tkulik** [comment]
Reopening this issue since it was verified in kabanero 0.7.0 release but also needs to be fixed in 0.6.0 with the new level of knative.   I have tested the fix in 0.7.0, not the workaround.

**Comment by tkulik** [comment]
The defect was verified with kabanero 0.7.0-alpha.1 release. Now need to verify it with 0.6.0 with the new version of knative.

  -  Installed rc6 of kabanero:

curl -s -O -L https://github.com/kabanero-io/kabanero-operator/releases/download/0.6.0-rc.6/install.sh

   - Upgraded env to the rc3 stack using oc edit kabanero -n kabanero cmd.

https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.6.0-rc.3/kabanero-stack-hub-index.yaml

  -  Ran the test with java-microprofile with knative enabled, and it worked fine. So the defect 304 is verified with kabanero 0.6.0 version. No workaround applied, I just used the fix provided in the new version of knative.



![image](https://user-images.githubusercontent.com/21961572/75503499-648d3480-599b-11ea-9de9-8f046eaa6e89.png)
