### ISSUE TITLE
create basic junit reporting to web page for nightly regression build

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#193]
Long term, the results of the nightly regression build will be passed to the cognitive build team's analysis engine, but for the short term, we need a basic reporting mechanism to indicate what tests passed and failed in our nightly regression run.  This could be as simple as some Junit reporting that gets wrapped into a web page.

**Comment by garypicher** [comment]
Issue #167 can be used for the longer-term solution that reports results to the cognitive systems.

**Comment by stevenschader** [comment]
I have enabled the ansible junit capability in our automation tree->https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/tree/master/automation/ansible-playbooks
