### ISSUE TITLE
nightly regression build should run tests from a separate repo

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#194]
Move the Kabanero Operator tests to a separate repository to be used for the test bucket
(For example, a new repo at kabanero-io/kabanero-regression-testing)

Modify the current Ansible role to run the tests in the test repo not from the Kabanero Operator repo.

    This should lay the groundwork for a generic test bucket that any given developer can submit tests to

**Comment by tomlinkusa** [comment]
New repo is created.

**Comment by tomlinkusa** [comment]
It is working now. And Steven fine-tuned the ideas.
