### ISSUE TITLE
define method for mapping test cases to applicable kabanero version

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#199]
Some test cases may only be applicable to a specific range of Kabanero releases.  We need to provide a way for a test case to indicate what versions it applies to.  By default, new test cases will probably apply to a given version or later, e.g. >= 0.7.0.  However, some test cases may become obsolete and apply to an older range, e.g. 0.5.0 through 0.7.0.

**Comment by marikaj123** [comment]
Moved out from this repo.
