### ISSUE TITLE
Update kabanero-regression-testing readme to have necessary prerequisites for running the tests

### ISSUE THREAD

**Issue by c1505** [kabanero-io/kabanero-foundation#206]
The tests need additional setup before they will run successfully outside of the internal automation.  

These are some of the suggestions from Steven of what is needed:
OS package jq
OS package podman or docker
oc cli
possibly the kabanero cli
connection setup to an existing OCP
docker login to the external registry ( I think )
kabanero branch or release XX installed
sample.yaml installed
Run the same version of the regression bucket XX

If it isn't sufficient we can further check our internal automation to see what is being done there that we might need to add as a step.

**Comment by marikaj123** [comment]
Moved out from this repo.
