### ISSUE TITLE
Restore after running a given test bucket

### ISSUE THREAD

**Issue by c1505** [kabanero-io/kabanero-foundation#208]
This will change a lot with openshift 4.4.  It may not be worth scripting prior to that depending on how long we want to continue to run on openshift 4.3.  

4.3 Restore steps are here https://docs.openshift.com/container-platform/4.3/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html .  

related to issue https://github.com/kabanero-io/kabanero-foundation/issues/168

**Comment by c1505** [comment]
If attempting for 4.3, make sure to have an openshift version greater than 4.3.2.  The documentation doesn't work for 4.3.0.  

In order to get the INITIAL_CLUSTER values , run this command from the master node after running backup:
```
./assets/bin/etcdctl --ca-file=./assets/backup/etcd-ca-bundle.crt --cert-file=./assets/backup/etcd-client.crt --key-file=./assets/backup/etcd-client.key --endpoints=https://localhost:2379 member list
```
Use the resulting name and peer_url values in the initial cluster variable in the format described in the documentation.  

Still waiting with red had support to get more details on verifying that the restore has completed successfully.  Step 3 `Verify that the Machine Configs have been applied.` Wasn't entirely clear to me.

**Comment by marikaj123** [comment]
Moved out from this repo.
