### ISSUE TITLE
Jane can get to Application Navigator from our unified console experience.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-foundation#34]

**Comment by cvignola** [comment]
Application Navigator work tracked by this issue:  https://github.ibm.com/WASCloudPrivate/roadmap-convergence/issues/871

**Comment by ianpartridge** [comment]
OK thanks, closing in favour of that issue.

**Comment by marikaj123** [comment]
The collection has a dependency on https://github.ibm.com/WASCloudPrivate/roadmap-convergenc

**Comment by marikaj123** [comment]
This issue should go under AppNav team.

**Comment by marikaj123** [comment]
@dianak2016 - Can a release be assigned to the Epic.

**Comment by dianak2016** [comment]
This is essentially a duplicate of https://github.com/kabanero-io/roadmap/issues/70 .  The epic 70 covers this and more, hence closing 34.
