### ISSUE TITLE
Upgrade Istio to 1.1.x level in install-kabanero-foundation.sh 

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#39]
The initial drop of the install script installs Istio using the pattern based on Knative.  That level of Istio is 1.0.7 and does not match the level that is preferred for the Tekton Dashboard 0.1.1. 
 Knative has removed this same Istio install from their distribution, and we need to find an alternate "demo" distribution.

The install script should check to see if Istio is already installed and if it is, skip Istio setup.

**Comment by dacleyra** [comment]
delivered
