### ISSUE TITLE
Create kabanero uninstall script 

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#40]
It is important to have uninstall script for kabanero to clean all the resources it installed and created. So that fresh re-install kabanero on the same cluster will work.

**Comment by tseelbach** [comment]
see also https://github.com/kabanero-io/kabanero-operator/issues/103

**Comment by stephenkinder** [comment]
The current example script should be merged into the foundation /scripts directory and let us iterate on making it better.  While it is not perfect, it is better than starting with nothing.

We would not hold up the release for this script, however.

**Comment by kaczyns** [comment]
Please try the uninstall script delivered in #76 and let us know if it needs work.
