### ISSUE TITLE
update readme for install-kabanero-foundation.sh script

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-foundation#43]
Please update https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts/README.md to remind users to change the  `my.openshift.master.default.subdomain` to their actual subdomain's name when running the following command:

`openshift_master_default_subdomain=my.openshift.master.default.subdomain ./install-kabanero-foundation.sh`

**Comment by mtamboli** [comment]
Actually, we should also change the command to add < >. I have many people cut and paste the command which does not work.

openshift_master_default_subdomain=<my.openshift.master.default.subdomain> ./install-kabanero-foundation.sh
