### ISSUE TITLE
cannot delete routes.serving.knative.dev and other istio/tekton crds  

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-foundation#44]
Using the script in the PR attached to   https://github.com/kabanero-io/kabanero-foundation/issues/40 I tried to delete "everything" .

The first runs using -r and -d deleted alot, but it ends up hanging and in the end routes.serving.knative.dev is still there:

./kab-uninstall.sh -r
---------- Deleting 'all' in istio-system ----------
No resources found
---------- Deleting 'all' in istio-operator ----------
No resources found
---------- Deleting 'all' in kabanero ----------
route.serving.knative.dev "appsody-hello-world" deleted
route.serving.knative.dev "webhooks-extension-sink" deleted
^C

 2019-08-31 06:07:35 ⌚  tsees-mbp in ~/github.com/kabanero-foundation/scripts
± |uninstall → origin ✓| → ./kab-uninstall.sh -d
Error from server (NotFound): apiservices.apiregistration.k8s.io "v1beta1.custom.metrics.k8s.io" not found
---------- Deleteing dangling resources for istio-system ----------
---------- Deleteing dangling resources for istio-operator ----------
---------- Deleteing dangling resources for kabanero ----------
route.serving.knative.dev "appsody-hello-world" deleted
^C

 2019-08-31 06:50:33 ⌚  tsees-mbp in ~/github.com/kabanero-foundation/scripts
 oc get all
NAME                                                URL                                                                             READY   REASON
route.serving.knative.dev/appsody-hello-world       http://appsody-hello-world.kabanero.my.openshift.master.default.subdomain       True    
route.serving.knative.dev/webhooks-extension-sink   http://webhooks-extension-sink.kabanero.my.openshift.master.default.subdomain   True    

 oc get crds --all-namespaces | grep knative
routes.serving.knative.dev              2019-08-02T18:35:52Z

Looks like istio and tekton aren't fully uninstalled either:
 oc get crds --all-namespaces
NAME                                    CREATED AT
adapters.config.istio.io                2019-08-02T18:33:31Z
alertmanagers.monitoring.coreos.com     2019-07-30T18:01:52Z
apikeys.config.istio.io                 2019-08-02T18:33:30Z
attributemanifests.config.istio.io      2019-08-02T18:33:30Z
authorizations.config.istio.io          2019-08-02T18:33:30Z
bundlebindings.automationbroker.io      2019-07-30T18:08:42Z
bundleinstances.automationbroker.io     2019-07-30T18:08:50Z
bundles.automationbroker.io             2019-07-30T18:08:46Z
bypasses.config.istio.io                2019-08-02T18:33:30Z
checknothings.config.istio.io           2019-08-02T18:33:30Z
circonuses.config.istio.io              2019-08-02T18:33:30Z
clustertasks.tekton.dev                 2019-08-02T18:35:42Z
deniers.config.istio.io                 2019-08-02T18:33:30Z
destinationrules.networking.istio.io    2019-08-02T18:33:30Z
edges.config.istio.io                   2019-08-02T18:33:31Z
envoyfilters.networking.istio.io        2019-08-02T18:33:30Z
extensions.dashboard.tekton.dev         2019-08-02T18:35:55Z
fluentds.config.istio.io                2019-08-02T18:33:30Z
gateways.networking.istio.io            2019-08-02T18:33:30Z
handlers.config.istio.io                2019-08-02T18:33:31Z
httpapispecbindings.config.istio.io     2019-08-02T18:33:30Z
httpapispecs.config.istio.io            2019-08-02T18:33:30Z
installs.tekton.dev                     2019-08-02T18:33:37Z
instances.config.istio.io               2019-08-02T18:33:31Z
kubernetesenvs.config.istio.io          2019-08-02T18:33:30Z
kuberneteses.config.istio.io            2019-08-02T18:33:30Z
listcheckers.config.istio.io            2019-08-02T18:33:30Z
listentries.config.istio.io             2019-08-02T18:33:30Z
logentries.config.istio.io              2019-08-02T18:33:30Z
memquotas.config.istio.io               2019-08-02T18:33:30Z
meshpolicies.authentication.istio.io    2019-08-02T18:33:30Z
metrics.config.istio.io                 2019-08-02T18:33:31Z
noops.config.istio.io                   2019-08-02T18:33:30Z
opas.config.istio.io                    2019-08-02T18:33:30Z
pipelineresources.tekton.dev            2019-08-02T18:35:43Z
pipelineruns.tekton.dev                 2019-08-02T18:35:43Z
pipelines.tekton.dev                    2019-08-02T18:35:42Z
policies.authentication.istio.io        2019-08-02T18:33:30Z
prometheuses.config.istio.io            2019-08-02T18:33:30Z
prometheuses.monitoring.coreos.com      2019-07-30T18:01:52Z
prometheusrules.monitoring.coreos.com   2019-07-30T18:01:52Z
quotas.config.istio.io                  2019-08-02T18:33:31Z
quotaspecbindings.config.istio.io       2019-08-02T18:33:30Z
quotaspecs.config.istio.io              2019-08-02T18:33:30Z
rbacconfigs.rbac.istio.io               2019-08-02T18:33:31Z
rbacs.config.istio.io                   2019-08-02T18:33:30Z
redisquotas.config.istio.io             2019-08-02T18:33:30Z
reportnothings.config.istio.io          2019-08-02T18:33:31Z
routes.serving.knative.dev              2019-08-02T18:35:52Z
rules.config.istio.io                   2019-08-02T18:33:30Z
servicecontrolreports.config.istio.io   2019-08-02T18:33:31Z
servicecontrols.config.istio.io         2019-08-02T18:33:30Z
serviceentries.networking.istio.io      2019-08-02T18:33:30Z
servicemonitors.monitoring.coreos.com   2019-07-30T18:01:52Z
servicerolebindings.rbac.istio.io       2019-08-02T18:33:31Z
serviceroles.rbac.istio.io              2019-08-02T18:33:31Z
signalfxs.config.istio.io               2019-08-02T18:33:30Z
solarwindses.config.istio.io            2019-08-02T18:33:30Z
stackdrivers.config.istio.io            2019-08-02T18:33:30Z
statsds.config.istio.io                 2019-08-02T18:33:30Z
stdios.config.istio.io                  2019-08-02T18:33:30Z
taskruns.tekton.dev                     2019-08-02T18:35:44Z
tasks.tekton.dev                        2019-08-02T18:35:44Z
templates.config.istio.io               2019-08-02T18:33:31Z
tracespans.config.istio.io              2019-08-02T18:33:31Z
virtualservices.networking.istio.io     2019-08-02T18:33:30Z

 oc get projects
NAME                                DISPLAY NAME   STATUS
default                                            Active
kabanero                                           Terminating
kube-public                                        Active
kube-service-catalog                               Active
kube-system                                        Active
management-infra                                   Active
openshift                                          Active
openshift-ansible-service-broker                   Active
openshift-console                                  Active
openshift-infra                                    Active
openshift-logging                                  Active
openshift-monitoring                               Active
openshift-node                                     Active
openshift-sdn                                      Active
openshift-template-service-broker                  Active
openshift-web-console                              Active

kabanero has been in Terminating state for several days (since i first tried to delete all)

**Comment by marikaj123** [comment]
Needs to provide uninstall script for the Oct release.

**Comment by kaczyns** [comment]
Please use the uninstall script delivered by #76 and let us know if it needs work.
