### ISSUE TITLE
OpenShift console shows an error for Kabanero namespace 

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#46]
I have kabanero installed using the scripts. When I login to OKD console, I see the following error after kabanero namespace is selected. 

![image](https://user-images.githubusercontent.com/29490950/64184179-13134b00-ce39-11e9-8bf2-27bbc0d759e7.png)

When you click on the `Open Metric URL`, It takes to a webpage https://hawkular-metrics.<OpenShift Cluster>/hawkular/metrics

![image](https://user-images.githubusercontent.com/29490950/64184503-89b04880-ce39-11e9-8622-e08b090804bd.png)

**Comment by garypicher** [comment]
@dacleyra took a look at this and his initial impression is that this problem is transient and doesn't impact function (he also suspects it might be an OKD issue).  Given that, I removed the release-0.1 label.

**Comment by mtamboli** [comment]
Closing this as this does not impact function and problem is not there on OCP4.2
