### ISSUE TITLE
Is install-kabanero-foundation.sh consumeable for Todd in a customized environment

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-foundation#77]
Re: https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/install-kabanero-foundation.sh

Kabanero yaml document should be colocated with install-kabanero-foundation.sh

or the location of the customized Kabanero yaml document should be able to be passed in as a parameter to install-kabanero-foundation.sh, otherwise when Todd customizes: 

https://github.com/kabanero-io/kabanero-operator/blob/master/config/samples/full.yaml

How will it know where the customized copy is?

**Comment by davco01a** [comment]
e.g.

# Create instance, and apply default collections
oc apply -n ${namespace} -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/${KABANERO_BRANCH}/config/samples/full.yaml

**Comment by davco01a** [comment]
having to edit a .sh file was inconvenient instead of passing in parms for any mutable values seems inconvenient

**Comment by davco01a** [comment]
the readme:  https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts
doesn’t really provide any explanation of how Todd would modify the script or what to modify in it prior to running it, is there doc being developed for that?

**Comment by davco01a** [comment]
is this consumeable for a new Todd encountering it for the first time?

**Comment by davco01a** [comment]
If Todd is going to have to modify the script, at the least there should specific comments indicating where he needs to make custom modifications in order to get it to run in his environment

**Comment by stephenkinder** [comment]
@davco01a there are several issues that you've documented in the same issue:

1.  the sample full.yaml belongs with the operator.  it is already in a "samples" directory which should indicate it is just that -- a sample.

1. i agree that we could have release argument on the script, I suggest you open a discrete issue for that new feature request.

1. i agree that the script could self-document that it is customizable -- that said, it is unclear what you mean by "run in his environment?"  We document the pre-requisites, what specific customization do you mean?

**Comment by davco01a** [comment]
@stevekinder-ibm  

1) the full.yaml will be customized by Todd and after that he has to point to it from the script, we should make this very clear with a comment before this line:

`oc apply -n ${namespace} -f https://raw.githubusercontent.com/kabanero-io/kabanero-operator/${KABANERO_BRANCH}/config/samples/full.yaml`

to modify it to pick up his cloned modified version of full.yaml.  Same goes for any and all variables or substitution values in the script

3) "Run in his environment" just means anything else that needs to be altered by Todd to specifically point to values in his config:

e.g. `namespace` , `KABANERO_BRANCH` and anything else Todd may have missed because he it too novice at reading this .sh file

**Comment by jgawor** [comment]
I would suggest to change the foundation install script not to deploy the full.yaml. Let the foundation script install every expect deploy an instance. That should be a separate step.

**Comment by davco01a** [comment]
+1 @jgawor

**Comment by davco01a** [comment]
Discussed with Steve, if we break out:

- remove deploy of default.yaml ( renamed and simplified from full.yaml ) as @jgawor has suggested from the kabanero foundation script
- document modifying default.yaml for specifying the location of the curated ( cloned version of the collection by Champ )
- and document how to perform the CR update from the default.yaml for the Kabanero Instance
- kabanero foundation script should then just run out of the box

**Comment by kaczyns** [comment]
First step of this is documenting the Kabanero CR and how to configure it.
https://github.com/kabanero-io/docs/pull/123

**Comment by marikaj123** [comment]
PR Link: https://github.com/kabanero-io/docs/pull/123

**Comment by kaczyns** [comment]
Second step is removing the CR instance from the install script:
#98

**Comment by marikaj123** [comment]
Is the issue ready to close?

**Comment by kaczyns** [comment]
@marikaj123 No this cannot close until kabanero-io/docs#123 is merged.

**Comment by kaczyns** [comment]
Thanks @alohr51  - I am closing this issue.
