### ISSUE TITLE
Kabanero pipelines use multiple collection repository

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#78]
Currently, during application development with appsody (init) certain version of collection repository is used. For example:
https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml

But these versions change for new release. How would kabanero pipelines handle applications built with multiple collection versions? It would probably be a Todd/Champ decision to  decide which versions to support though. I have seen pipeline tasks failing when the application is created with old collections.

**Comment by stephenkinder** [comment]
There is an intention to follow semver.org rules for versioning.   At the moment, however, it is not possible to have two different semantically different Appsody stacks in the same Appsody application hub.  E.g. java-microprofile versions 0.2.x and 0.3.x.   The developer can only specify the name of the stack, the version is not selectable.

**Comment by marikaj123** [comment]
@sympatheticmoose - Can you please provide us with the link to the Appsody issue for tracking the work progress.

**Comment by marikaj123** [comment]
Actions:
- Monica and Steve K will discuss it further

**Comment by marikaj123** [comment]
@stevekinder-ibm - Do we know at what release to fix the issue?

**Comment by marikaj123** [comment]
Will implement a workaorund for 0.5.0: Will reuire to have two hubs.  
In later releases will provide some design changes.

**Comment by mtamboli** [comment]
@stephenkinder @marikaj123 This issue is about how kabanero will handle applications built with multiple versions of appsody stack. This feature is supported by kabanero 0.5. Will verify it soon.

**Comment by mtamboli** [comment]
Closing this issue as kabanero 0.5 support multiple versions and also new design supporting this in 0.6.
