### ISSUE TITLE
Add mustgather script

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-foundation#79]
A script to collection relevant debug information 

Execute the script `kabanero-mustgather.sh` while logged in as a cluster-admin to gather information about the state of the kabanero foundation components, which includes appsody, istio, kabanero, knative, and tekton. The script collections `get` and `describe` information about these components, as well the `pod logs`.

**Comment by jgawor** [comment]
i'm not sure how this script will be structured but i think it would be good to come up with a set of generic functions or separate scripts for capturing the information. that way, we could use them to collect information for different namespaces, additional pods, etc. - as users deploy the apps into their own namespaces or we add additional components.

it might also be good to have `<component>-mustgather.sh` as different components might have different set of data to collect.

**Comment by marikaj123** [comment]
@dacleyra - What are the next steps for the issue to be closed?

**Comment by dacleyra** [comment]
merged, close
