### ISSUE TITLE
Update install script to use operator `default.yaml` in release 0.2.0

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-foundation#84]
The `full.yaml` is no longer appropriate since it includes all of the possible configuration options, many of which are not relevant to most users.  We should use `default.yaml` instead.  Since the install script references named releases, when we switch to 0.2.0 we should change `full.yaml` to `default.yaml` in the install script.

**Comment by marikaj123** [comment]
This PR closes this issue.https://github.com/kabanero-io/kabanero-foundation/pull/89
