### ISSUE TITLE
Kabanero dependent project release yaml

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#86]
As part of preparing for foundational automation, it is necessary to build a list of dependencies that can be used in a codified way from a central control point.  By declaring the dependencies in YAML form, we can provide the source for self-describing documentation, but also use it for project automation.

**Comment by marikaj123** [comment]
@garypicher - we need to close on this issue before we can close on its Epic by this Friday.

**Comment by marikaj123** [comment]
@according to @garypicher - the work was not originally scheduled for v0.2.  Therefore, I am moving it to release 0.3.

**Comment by marikaj123** [comment]
Targeted for v0.3.0

**Comment by marikaj123** [comment]
According to Gary work is complete and can be closed.
