### ISSUE TITLE
Testing and documentation of upgrade of 0.1.2 to 0.2.0 migration.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#88]
We need to test and document the requirements for upgrading the kabanero-foundation, even if it is just a normal operator upgrade.

**Comment by marikaj123** [comment]
@mingcyu - Does the issue need ID involvement and the 'ID-required' label?

**Comment by kaczyns** [comment]
I did some initial tests (not to replace what SVT will do) using two methods to upgrade 0.2.0:
1) Just re-ran the 0.2.0 version of the install script.  That went fine.  I'm not sure we'd want to recommend that in general, but it works for now.
2) Upgraded just the operator deployment and CRD (the pieces that changed).  Then after the operator comes up, edit by `Kabanero` CR instance to point to version 0.2.0, and to collection version 0.2.0.  That also worked fine.

I guess at this point I'd prefer to have an upgrade script or instructions that tell the user to upgrade the operator to the latest version.  Then go inspect the `Kabanero` instance and modify it to the newer version when they are ready (the new version of the operator will support the old version of Kabanero for as long as they want to stay there).  Of course this will all fall apart when one of the pre-reqs changes (ie tekton upgrade, knative upgrade).  It's also subject to change when we get to OCP 4.x.  

Feedback is welcome :-)

**Comment by marikaj123** [comment]
@gecock - Your feedback would be appreciated after trying out the actual steps.

**Comment by kaczyns** [comment]
@marikaj123 @gecock I am going to try to get to this today... I've been focusing on the install/curation path with Monica.

**Comment by kaczyns** [comment]
@gecock @mtamboli Please see:
https://github.com/kaczyns/kabanero-foundation/tree/upgradeKabanero/scripts 

This is the first attempt at the upgrade procedure.  Please let me know what you think.

I tested it by first installing 0.1.2 using the install script.  Then, I used the upgrade script.  After the script runs, you should see the `kabanero-operator` pod restart with the new container version (mine went from `0.1.2` to `0.2.0-rc.1`).  You can do an `oc get pods -n kabanero` to see the list of pods, and then `oc get pod xxx -n kabanero -o yaml` to inspect it (replace xxx with the pod name).

After you run the script, you have to manually change the Kabanero CR instances, to use the new version.  If the Kabanero CR instance has a `version: someversion` attribute, you need to change it to the new version (like `0.2.0`).  If it does not have a version, then it should automatically be upgraded.  If you are using the default collections, and you want to use the new version, that needs to be manually updated too.

**Comment by gecock** [comment]
Thanks @kaczyns. I'll throw in my initial feedback that the script works and the doc that goes with it was good enough to get my Kabanero instance updated successfully enough that my app continued to run fine. 

I will be continuing to verify things this week.

**Comment by marikaj123** [comment]
@kaczyns and @jantley-ibm - Do we need a PR for documentation to be reviewed by ID?

**Comment by kaczyns** [comment]
@marikaj123 Now that @gecock has tested the upgrade information from the readme, I need to copy it to the doc repo with a new PR.  I will try to do that tomorrow (Wednesday).

**Comment by kaczyns** [comment]
@marikaj123 I opened kabanero-io/docs#137 to document the upgrade script.  I assigned @jantley-ibm as the ID reviewer.  Please change that if it's not appropriate.  Thanks!

**Comment by marikaj123** [comment]
Jeff is going to merge the PR.

**Comment by marikaj123** [comment]
@alohr51 - Do we have the work published?

**Comment by jantley-ibm** [comment]
Work is published @marikaj123 https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html

**Comment by marikaj123** [comment]
@alohr51 - Can the issue be closed?
