### ISSUE TITLE
Dependent Project upgrade Tekton 0.7 Pipelines

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#93]
The webhook extensions and dashboard have been updated to support Tekton 0.7 and it would be better sooner, rather than later to do the upgrade because the pipeline syntax are incompatible. 

We need to define,  understand:

- the dependencies of Tekton 0.7, and if they are compatible with the current versions of the Knative and Istio dependent products -- they may also need to be upgraded.
- upgrade Tekton and any dependent products
- define the upgrade procedure from Kabanero 0.2.0 with a current collection active, with pipelines that have incompatible syntax and Appsody applications that are deployed into targetNameSpaces.
- update the foundation dependent project YAML

**Comment by marikaj123** [comment]
@stevekinder-ibm - Who can own the issue?

**Comment by stephenkinder** [comment]
I added the blocked tag, to indicate we are waiting for the Tekton Dashboard and Tekton Webhook Extension to be updated to Tekton 0.7 + Knative 0.7.1 in support of OCP 4.2.  This is already marked a child of the epic for 0.3.0.  

The operator team owns doing this when the Tekton pieces have been delivered.  I assigned to the operator team to sort out.

**Comment by dacleyra** [comment]
The install procedure changes to use OLM, and is in progress as part of this PR.
https://github.com/kabanero-io/kabanero-foundation/pull/112

**Comment by marikaj123** [comment]
@gecock and @mtamboli - Tekton dashboard 0.2.1 and wehooks extension release 0.2.1 will be releases in a day or two.

**Comment by marikaj123** [comment]
@kvijai82 - Tekton dashboard 0.2.1 and wehooks extension release 0.2.1 will be released in a day or two. Kabanero v0.3.0 will be using Tekton pipelline 0..7.0 with Tekton dashboard 0.2.1 and wehooks extension release 0.2.1 with OCP 4.2.
