### ISSUE TITLE
Dependent Project Upgrade - Tekton Extension 0.2.0.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-foundation#94]
The Tekton extension has been updated to depend on Tekton 0.7.  It is unclear to me at this time if the extension has to be upgraded at the same time or after the upgrade to Tekton 0.7.  It may be easier to address simultaneously -- however, we do have to support the upgrade of customers from Kab 0.2.0 to Kab 0.3.0.

**Comment by marikaj123** [comment]
@stephenkinder - who can own the issue?

**Comment by kaczyns** [comment]
@stephenkinder I am assuming that if we move to OCP 4.2 for Kab 0.3.0, we won't have to support an upgrade from Kab 0.2.0 to Kab 0.3.0.  Please let me know if I'm not understanding correctly.

**Comment by marikaj123** [comment]
@kaczyns - Tekton dashboard 0.2.1 and webhooks extension release 0.2.1 will be released in a day or two.

**Comment by marikaj123** [comment]
@kaczyns - Is this issue ready to close?

**Comment by kaczyns** [comment]
Yes, I will close it now.
